version: '3'
networks:
  app-tier:
    driver: bridge
services:
  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: hellokoding
      MYSQL_ROOT_HOST: '%'
    expose:
      # Opens port 3306 on the container
      - '3306'
    ports:
    - "3306:3306"
    restart: always
    #where data is persisted
    volumes:
    - my-datavolume:/var/lib/mysql
    networks:
      - app-tier
 
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - MYSQL_USERNAME=test
       - MYSQL_ROOT_PASSWORD=hellokoding
       - PMA_HOST=hk-mysql
      restart: always
      ports:
       - 9080:80
      networks:
       - app-tier
      volumes:
       - /sessions
       - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - hk-mysql
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
      - app-tier
#Name our volume
volumes:
  my-datavolume:
