version: '3'
networks:
  app-tier:
    driver: bridge
services:
  hk-postgres:
    container_name: hk-postgres
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=hellokoding
    expose:
      # Opens port 3306 on the container
      - '5432'
    ports:
    - "5432:5432"
    restart: always
    #where data is persisted
    volumes:
    - my-datavolume:/var/lib/mysql
    networks:
      - app-tier

  app:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - hk-postgres
    networks:
      - app-tier
#Name our volume
volumes:
  my-datavolume:
