version: "3"
services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - MYSQL_USERNAME=test
       - MYSQL_ROOT_PASSWORD=hellokoding
       - PMA_HOST=172.19.0.2
      restart: always
      ports:
       - 9080:80
      networks:
       - springdatarest-mysql-single_app-tier
      volumes:
       - /sessions
       - ~devops/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
networks:
   springdatarest-mysql-single_default:
     external: true
